Release v4.3.0 merge develop into main (#2681)
* fix:batch offset Decoding failed

* fix:batch offset Decoding failed

* fix: Update criteria handling in MetadataInstancesServiceImpl for improved query efficiency

* fix: TAP-6286 fix for create update conditions index

* fix:add decoding_batch_offset_failed test case

* TAP-6360: feat Data verification supports ignoring time accuracy

* feat: TAP-6051 DB - Kafka Transformer

Closes TAP-6051

* feat:Data verification supports ignoring time accuracy add testcase

* feat:Disabled HuaweiDrsKafkaConvertorNodeTest testSuccess case

* fix:update jacoco version

* fix:update iengine jacoco version

* TAP-6441:Unit test failed after upgrading jdk17

* add test case

* change loglevel to info

* 更新 mr-ci.yaml，修改构建和测试步骤的 client_payload，添加 RUN_TEST 参数以支持自动测试，并简化工作流步骤。

* 更新 mr-ci.yaml，修改 client_payload 中的 propagate_failure 参数为 false，以防止构建失败时不传播错误。

* 更新 mr-ci.yaml，重命名构建步骤为 Build-Deploy-Test，并移除关闭测试环境的相关步骤，以简化工作流配置。

* 更新 mr-ci.yaml，添加条件判断以控制构建步骤的执行，确保在特定情况下不触发构建。

* fix unit test case run on jdk17 error

* 更新 mr-ci.yaml，将 wait_interval 从 10 修改为 60，以延长构建步骤的等待时间。

* feat: TAP-6310
add delete policy

* revert auth config

* fix auth bugs

* fix code reliability

* Refactor code to avoid code duplication

* Refactor code to avoid code duplication

* Refactor code to avoid code duplication

* 更新 mr-ci.yaml，将构建步骤名称从 Push-Code-To-GOGS 修改为 Push-Code-To-Gitee，并调整相关依赖关系，以确保工作流的正确性。

* fix: TAP-6419 resolve log aop npe

* fix:Support illegal time

* fix: Temporarily fix the problem of inaccessible tm interface

The preliminary investigation is caused by the introduction of mcp dependencies, which temporarily comments on the dependencies and waits for repair of PR

* fix auth bug

* add mcp into tm

* feat: TAP-6051 DB - Kafka Transformer

Closes TAP-6051

* fix: Fix engine cannot login issue

(cherry picked from commit cf06bf81a0b400169c459b76ce9fb36876615c4e)

* feat: TAP-5501 add task-inspect CDC Inspect features.

* feat: TAP-5501 add testcase.

* feat: TAP-5501 add testcase.

* feat: TAP-5501 add testcase.

* feat: TAP-5501 task-inspect add testcase.

* fix: TAP-6463 inspect count error display alarm time

* fix: TAP-6246 fix unit test

* fix: TAP-6493 agent can not start when access code is default value

* fix:Upgrade dependencies to resolve new vulnerabilities

* fix: TAP-6559 ldp query table name with case insensitive

* fix: 更新构建脚本以支持异步分析器的下载和准备，同时在Dockerfile中添加Java 17的安装步骤，并优化async-profiler的处理方式。

* 重构构建工作流，使用新的同步代码脚本替代原有的多个checkout步骤，简化代码管理流程，并添加必要的密钥配置以支持Gitee的代码同步。

* fix: 重构Push-Code-To-Gitee步骤，使用新的同步代码工作流替代多个checkout步骤，简化配置并添加必要的密钥支持。

* fix: 更新构建工作流，调整Sync-Code-to-Internal-Repo步骤以使用Set-Branch的输出，确保正确的tapdata分支传递。

* TAP-5945 feat(iengine): support truncate

* fix(iengine): change truncateTableEvent name

* fix unit case

* fix: 更新构建工作流，调整Java版本设置以支持不同版本的构建，确保tapdata和连接器的编译过程顺利进行。

* fix: 更新构建工作流，移除不必要的tapdata-enterprise-web目录，优化前端代码检出步骤以支持tapdata-web的克隆。

* fix: 更新构建工作流，添加Node.js版本管理，确保前端构建使用指定的Node版本，并优化pnpm配置命令。

* fix:kafka TapTest failed-develop

* fix: 更新构建工作流，优化Node.js版本设置和pnpm配置，确保前端构建过程顺利进行。

* fix: 更新Dockerfile，添加supervisor、python3-pip和pipx的安装，并通过pipx安装tapflow，优化环境变量设置。

* fix: 更新Dockerfile，添加对不同架构的JDK下载和配置，优化Java环境设置，确保在x86_64和aarch64架构上均能正确安装Java 17。

* fix truncateTableEvent name

* fix: 在docker-entrypoint.sh中添加通用JVM参数，以优化Java应用的启动配置，确保在不同环境下的兼容性和性能。

* fix: TAP-6244 optimize pg error code when create publication failed

* fix: TAP-6244 add unit test

* fix: TAP-6489 task-inspect add recover logics.

* perf: Delete useless prints

* perf: Optimize code

* fix: Fixed the problem that the task could not be stopped in error status

* fix: TAP-6489 task-inspect Optimize the verification queue.

* fix: TAP-6489 task-inspect remove not used apis.

* fix: TAP-6637 Tasks with union + master-slave merge nodes cannot run normally

Closes TAP-6637

* fix: Fix error: java.lang.NoClassDefFoundError: org/apache/commons/collections/CollectionUtils

* fix: TAP-6489 task-inspect add alarm feature.

* fix: TAP-6489 task-inspect MD5 test case use complex chars.

* fix: TAP-6662 send email failed by proxy smtp

* fix: TAP-6489 task-inspect fixed sample rate control and add recovered testcase.

* fix: TAP-6660 can not find the corresponding tasks after searching the table name in the ldp

* fix: TAP-6641 resolve ObservableAspectTaskUtil npe

* feat: Add endpoint to retrieve database types and PDK hashes

* fix: TAP-6570 optimize log

* fix:sonarQube Scanning coverage is not available

* fix: Ignore QueryMapper log info, when the task query filter include 'dag.nodes.*' print log.

* fix: TAP-6489 task-inspect fixed testcase error.

* fix: TAP-6244 resolve changes request

* fix: TAP-6641 add logs when retrieve raw failed

* fix: TAP-6623 remove id from set document if metadata instance already exists when insert metadata dtos

* fix: TAP-6623 resolve changes request

* fix: TAP-6244 fix unit test

* fix: TAP-6722 The system alarm page will report IllegalArgumentException

* fix: TAP-6722 The system alarm page will report IllegalArgumentException

* fix: TAP-6244 resolve changes request

* fix: TAP-6244 fix unit test

* fix: TAP-6635 MySQL - SQL Server synchronization index error

* fix: fixed task-inspect sync rename table can't found schemas.

* feat: TAP-6552 nine bridge check service

* fix: task-inspect ignore TaskInspect of Task SyncType.

* fix:Byte primary key verification failed

* fix: TAP-6743 fix for skip error event aspect task leads to oom

* fix: TAP-6743 add unit test

* fix: TAP-6743 add unit test

* TAP-6682:feat(tm):import inspect Task

* TAP-6597feat(engine):feat ignore Precision length not equals and Ignoring precision 3

* feat: file input stream connector

* TAP-5885:feat(tm):custom alarm email

* fix(tm):Handling truncation

* refactor: Enhance email alarm content formatting for various task notifications in 4.0-1.json, improving readability and visual appeal.

* feat(tm):import inspect task

* fix:fix unit case

* fix(tm):oss can not overwrite importTask

* fix:add TASK_INSPECT_DIFFERENCE template

* fix(tm):remove inspectServiceImpl sorna

* fix: TAP-6796 TM oauth/token API can not get token

Closes TAP-6796

* refactor: Update email alarm content structure in 4.0-1.json for improved formatting and user experience

* fix: TAP-6796 TM oauth/token API can not get token

Closes TAP-6796

* fix: Fix merge issues

* Update RELEASE

* fix: Fix merge issues

* fix: TAP-6796 TM oauth/token API can not get token

Closes TAP-6796

* fix: TAP-6721 mongos(3.4)--》mongos(6.0)， Full field verification, error: Can't find a codec for CodecCacheKey

* feat:TAP-5816 Support export repair sql

* fix: TAP-6721 add unit test

* fix:pom.xml dependency organization

* feat:TAP-5816 Support export repair sql

* fix: TAP-6799 Fixed the issue where the master-slave merge, and the join key was updated from non-existence to exist, causing the inability to merge. (#2659)

Closes TAP-6799

* fix: TAP-6818 TapData has been upgraded from a low version (3.10.0) to a high version (3.27.0), and many tasks have encountered errors where classes cannot be found java.lang.ClassNotFoundException: io.tapdata.dummy.po.DummyOffset

* fix: TAP-6818 TapData has been upgraded from a low version (3.10.0) to a high version (3.27.0), and many tasks have encountered errors where classes cannot be found java.lang.ClassNotFoundException: io.tapdata.dummy.po.DummyOffset

* fix:Task monitoring, milestones, full table details, full completion time alignment

* feat: tapdata-test

* feat: tapdata-test

* feat: tapdata-test

* fix:Sonatype Security Scan Alerts for TapData v4.1.0

* feat: tapdata-test

* fix:Data Validation Task Search Issue System Error

* fix: TAP-6853 The field rename becomes invalid after capitalization

* feat: tapdata-test

* fix: TAP-6823 Master-slave merge task, only one slave node is retained after disabling the node, and it will not stop after full synchronization is completed

* feat: tapdata-test

* TAP-5221:feat js support unset

* feat: tapdata-test

* Update RELEASE

Update RELEASE

* feat: tapdata-test

* feat: tapdata-test mysql hotspot problem

* fix: Fixed the bug where the target multi-threaded write cannot correctly obtain the write policy

* fix: Fixed the bug where the target multi-threaded write cannot correctly obtain the write policy

* feat: tapdata-test oracle

* feat: tapdata-test write batch

* feat: tapdata-test oracle

* fix: TAP-6943 fix for migrate task to remove add sub fields in targer node

* fix: TAP-6943 fix for migrate task to remove add sub fields in targer node

* fix: shareCDC can use increaseReadSize

* fix: add cdcConcurrent cdcConcurrentWriteNum for shareCDC

* fix: add cdcConcurrent cdcConcurrentWriteNum for shareCDC

* fix: remove sonar tapdata-test

* fix: remove sonar tapdata-test

* fix: remove sonar tapdata-test

* fix: remove sonar tapdata-test

---------

Co-authored-by: hardy <2545433047@qq.com>
Co-authored-by: Feynman <xufei@tapdata.io>
Co-authored-by: mnianqi <mnq0626@163.com>
Co-authored-by: jarad0628 <coolgj@163.com>
Co-authored-by: Leon <lirufei0808@gmail.com>
Co-authored-by: dreamcoin1998 <gaojunbin98@gmail.com>
Co-authored-by: jackin-code <452725950@qq.com>
Co-authored-by: harsen <harsen@tapdata.io>
Co-authored-by: ljvv7 <fes504200361@qq.com>