Release v3.20.0 Merge develop into main (#2440)
* fix(iengine):update unit case

* fix: TAP-5206 Multiple retries of shared mining task resulted in oom

* fix: TAP-5206 resolve sonar issue

* update query log api

* fix: TAP-5206 fix unit test failure

* support include log tag and exclude log tag

* add dynamic description parameters

* update unit case

* fix(iengine):update unit case

* fix(iengine):update error code

* fix: TAP-5206 Multiple retries of shared mining task resulted in oom

* fix(iengine):TAP-5228 inspect support boolean compare with not boolean value

* fix(iengine):add unit case

* fix(iengine):update unit case

* fix(iengine): change to boolean return value

* fix: TAP-5005 Revise the description of Maputls in the JS API documentation

* fix(tm):add some log

* fix not update milesone retry status when cdc finish

* fix(iengine): Fix polling cdc bug

exception: / by zero

* fix(tm):add some log

* add catch data feature

* fix(tm):add update log

* fix:js not found import class develop

* fix(tm):add log for tm

* TAP-5265:fix js not found import class develop

* update unit test case

* TAP-5257:fix(tm): transformer will cover old task setting

* add unit test case

* update unit test case

* optimization milestone describe error code

* fix(tm):change SYNC_TYPE with constant

* fix(tm):convert string to constant

* fix(tm): exclusionQueryField type

* fix(tm):exclusion type

* fix: fix for cloud version fully hosted public engine CPU usage rate of 100%

* fix: fix for cloud version fully hosted public engine CPU usage rate of 100%

* fix: fix for cloud version fully hosted public engine CPU usage rate of 100%

* feat(iengine): TAP-5906 update error code

* fix(iengine): Fix task preview npe bug

* fix(iengine):update error code

* feat(iengine): TAP-5906 update error code

* update data catch feature

* update query cache data by user input string

* feat(iengine): TAP-5906 update error code

* update unit test case

* update unit test case

* feat(iengine): TAP-5906 code review

* add table name into catch data

* feat(iengine): TAP-5906 fix unit test

* optimization catch data code

* optimization catch data code

* tapce workflow test

* tapce workflow test

* feat(TM):TAP-5253 add custom collate

* feat(iengine): TAP-5906 add unit test

* feat(iengine): TAP-5906 add unit test

* feat(iengine): TAP-3360 engine can start without mongodb config

* update catch data

* feat(iengine): TAP-3360 add unit test

* update data serialize config for ObjectId

* Update ConnectorManager.java

* feat(iengine):TAP-5253 support custom collate

* optimization json serialize for catch data

* feat(iengine): TAP-3360 add unit test

* fix(iengine):update unit case

* fix(iengine):remove unit case

* update unit test case

* fix(manager):add sonar config

* update processCompleted

* feat: TAP-5193 MongoDB supports SSL configuration connection

* feat(iengine): TAP-5193 MongoDB supports SSL configuration connection

* feat(iengine): TAP-5193 MongoDB supports SSL configuration connection

* optimization code for process tap event

* feat(iengine): TAP-3360 engine can start without mongodb config

* fix: add scan-tapdata into mr-ci.yaml

* add unit test case

* fix: TAP-5304 admin user allows to operate all tags

* feat(iengine): TAP-3360 resolve sonar issue

* feat: TAP-5193 resolve sonar issue

* update unit test

* fix: TAP-5304 add unit test

* Fix merge issue

* Fix merge issue

* fix:TAP-5331_task_index_error

* add download file api

* Fix batch offset status issue

* fix: TAP-5193 update ssl environment variables name

* fix:TAP-5331_task_index_error

* fix:TAP-5331_task_index_error

* add test case

* fix:TAP-5331_task_index_error

* feat: TAP-5286 optimize ad login exception

* fix: TAP-5193 fix log mongo config

* feat: TAP-5291 support single session login

* Fix batch offset status issue

* Fix target throw error issue

* fix: TAP-4874 Fixed a situation where disabling a source node in the merge scenario could not be completed.

* fix: TAP-5250 After the indicator is cleared by ttl, the dynamically added table of the copy task does not work

* fix: TAP-5250 After the indicator is cleared by ttl, the dynamically added table of the copy task does not work

* feat: TAP-5286 optimize ad login exception

* optimization log

* Fix rename fields bug

* TAP-5350 fix(tm): Migrating tasks The migration task time injection is empty

* fix(iengine):TAP-5303 add Multi thread paritionValue error code

* fix:js model deduction failed

* fix:js model deduction failed

* refactor: add oem replace

* refactor: update oem replace

* refactor: add datapp_normal oem replace

* feat: TAP-5290 record and store management user or role actions

* feat: TAP-5290 record and store management user or role actions

* feat: TAP-5290 add unit test

* feat: TAP-5290 add unit test

* feat: TAP-5290 add unit test

* fix(iengine):add unit case

* feat: TAP-5170 When selecting a table with only a primary key and matching it with a regular expression to synchronize, the task of adding a table without a primary key will keep logging the discovery of the new table

* feat: TAP-5029 support refresh access code

* UPDATE RELEASE

* fix:tm、tcm merge

* fix(iengine): TAP-5369 TapTable.getNameFieldMap() item order should be same with datasource load schema, but it's not same now

Closes TAP-5369

* fix:TAP-5295 Failed to delete cluster

* update error-code dependency version to 1.2

* update dependency version

* fix:TAP-5295 Failed to delete cluster

* fix(iengine):TAP-5363 fix can not throw exception with tableName

* update dependency version

* update dependency version

* update dependency version

* fix:TAP-5295 Failed to delete cluster

* update dependency version

* feat: TAP-5291 resolve change request

* update unit test case

* feat: TAP-5170 When selecting a table with only a primary key and matching it with a regular expression to synchronize, the task of adding a table without a primary key will keep logging the discovery of the new table

* feat: TAP-5291 add unit test

* feat: TAP-5170 add unit test

* fix: TAP-5282 add operation log when deleting task

* feat(iengine): TAP-5377 Add default universal solution to error code

Closes TAP-5377

* update unit test case

* update unit test case

* fix: TAP-5002 JS Processor objectId to mongo DB error

* fix: TAP-5002 JS Processor objectId to mongo DB error

* upgrade dependency version

* update dependency version

* fix: TAP-5029 fix for sub account refresh and add user log after refreshing access code

* fix: TAP-5002 resolve changes request

* feat: TAP-5339 Webhook alarm without permission control

* fix when the FE version is lower, WebSocket cannot connect server. Like Cloud env

* fix:tm、tcm merge

* fix:tm、tcm merge

* fix:tm、tcm merge

* fix:tm、tcm merge

* fix:tcm tm merge pom.xml

* fix:tcm tm merge pom.xml

* fix:tcm tm merge pom.xml

* fix info log lost

* update unit test case

* fix:TAP-5413 AutoTest get Trace Log

* fix:TCM、TM merge deployment

* fix:cloud mail bug

* fix:ssl send mail bug

* fix:ssl send mail bug

---------

Co-authored-by: ljvv7 <fes504200361@qq.com>
Co-authored-by: mnianqi <mnq0626@163.com>
Co-authored-by: Leon <lirufei0808@gmail.com>
Co-authored-by: hardy <2545433047@qq.com>
Co-authored-by: zhoupeng <peng@tapdata.io>
Co-authored-by: mnianqi <139107099+mnianqi@users.noreply.github.com>
Co-authored-by: dreamcoin1998 <gaojunbin98@gmail.com>
Co-authored-by: harsen <harsen@tapdata.io>
Co-authored-by: Feynman <xufei@tapdata.io>
Co-authored-by: jackin-code <452725950@qq.com>