Release-v3.18.0 merge develop into main (#2375)
* Fix: TAP-5126 Fixed source node add virtual field if node no any links.

* fix: ldp display fdm metadata instance

* fix: ldp display fdm metadata instance

* fix: ldp display fdm metadata instance

* fix: TAP-5045 qps size expand several times larger than the actual size

* TAP-5062:fix cloud mongo net out huge

* TAP-5062:fix cloud mongo net out huge

* Feat: TAP-4020 Add no primary key table sync mode switch.

* Fix: TAP-4020 Fixed testcase error.

* TAP-5062:fix queryRecords net out huge

* TAP-5062:fix queryRecords net out huge

* feat: TAP-5089 Error code framework improvements

1. Error codes add dynamic description information capabilities;
2. update error code and pdk api version

Closes TAP-5089

* feat: TAP-5089 Error code framework improvements

pdk支持自定义错误码

Closes TAP-5089

* UPDATE RELEASE

* fix: TAP-5143 There are field names A and B, if field A->B and field B->C, the model deduction will lose field B

* feat: TAP-5089 Error code framework improvements

unit tests

Closes TAP-5089

* feat: TAP-4533 Metrics optimization

Fix failed unit tests

Closes TAP-4533

* impl processor log split

* feat: mongo error code for 16M limit

* feat(iengine):TAP-5090 update error codes

* fix: TAP-5143 resolve sonar issue

* feat(iengine):TAP-5090 update error code

* fix merge error

* TAP-4533:add unit test case

* fix merge error

* TAP-4533:add unit test case

* fix test case error

* fix test case error

* fix code smell

* fix code smell

* perf: Optimize the performance of task preview interface

Closes TAP-4842

* Fix compile error

* add unit test case

* update unit test case

* fix(task preview): Fixed the problem that when targetPath is null or empty string, an error will be reported or the merged result will not meet expectations.

* fix: TAP-5153 Save task will prompt that it is not allowed after renew failed

* fix(task preview): unit tests

* fix: TAP-5143 fieldInfoTempMaps is only built once

* fix(task preview): unit tests

* feat: add tap log trace level

* feat(error code): TAP-5089 Error code optimization

Improved error code information acquisition interface

Closes TAP-5089

* fix: Fix failure unit tests

* Tap 5089 Error code optimization (#2327)

* feat: mongo error code for 16M limit

* feat: add tap log trace level

* feat(error code): TAP-5089 Error code optimization

Improved error code information acquisition interface

Closes TAP-5089

* fix: Fix failure unit tests

---------

Co-authored-by: jarad0628 <coolgj@163.com>

* fix: TAP-5153 unit test

* add retry status for milestone

* fix: TAP-5143 unit test

* TAP-4533:fix sonar

* TAP-4533:iengine-app pom.xml

* add implements method for interface Log

* remove trace log method

* upgrade pdk runner version to 1.11

* fix: TAP-5143 There are field names A and B, if field A->B and field B->C, the model deduction will lose field B

* revert pdk runner version to 1.10

* add unit test case

* add unit test case

* add unit test case

* feat: TAP-5046 migrate task should clean batch offset when remove current sync table

* update RetryLifeCycleAspect

* feat: add error code for connection test

* update unit test case

* update unit test case

* optimizing the code

* fix Duplicated Lines

* feat: TAP-5046 resolve unit test failure

* feat: TAP-5144 format with yyyy-MM-dd'T'HH:mm:ss'Z when field dataflow processor convert datetime to string

* fix mileston entity bug

* fix(task preview): unit tests

* TAP-5061:fix cloud Permission RoleMapping Large flow

* TAP-5061:fix cloud Permission RoleMapping Large flow

* feat: add dynamicDescriptionParameters for connection test

* feat: TAP-5152 Supported mongodb lower to mongodb IUD and Replace operations

* upgrade tapdata-pdk-api version to 1.4.1

* fix(task preview): unit tests

* fix(task preview): fix sonar bugs

* fix(task preview): unit tests

* TAP-4533:fix

* TAP-4533:fix

* fix(task preview): unit tests

* TAP-4533:fix

* fix(task preview): unit tests

* fix(task preview): unit tests

* fix(task preview): fix sonar bugs

* feat(iengine):update error code

* fix(iengine):update error code

* fix(iengine):update error code

* fix(iengine):fix unit case

* fix(iengine):fix unit case failed

* fix(iengine):update unit case

* fix(iengine):update unit case

* Fix merge issue and failed unit tests

* fix(iengine):update unit case

* fix(iengine):update unit case

* fix(iengine):add unit case

* fix(iengine):add unit case

* fix(iengine):add unit case

* fix: dynamic add table and ddl

* fix(iengine): Fix performance issue

The statistics module temporarily switches back to the old version logic to avoid affecting performance and awaits subsequent adjustments.

* fix(iengine): Change duplicate info logs to debug

* fix: TAP-5183 The task progress keeps showing 50%

* perf(iengine): TAP-5154 Master-slave merge improves logs to facilitate finding cache table names

Closes TAP-5154

* fix: TAP-5180 prompt no permission when delete tags by other user

* TAP-5061:fix cloud Permission RoleMapping Large flow

* Fix failed unit test

* fix: upgrade plugin pom

* TAP-5061:fix cloud Permission RoleMapping Large flow

* fix change table monitor associateId bug

* Fix can not create sub partition bug

* add unit test for restartPdkConnector

* add unit test for table monitor start method

* fix reliability rating on new code

* update unit test for table monitor start method

* fix: TAP-5190 Resolve the unauthorized access vulnerability of Spring Boot Actuator

* fix: TAP-5181 source node reload schema prompt System error: null

* refactor log storage

* TAP-5211:fix(TM):fix loading schema slow

* fix(tm):TAP-5211 loading schema slow

* fix(TM):TAP-5223 console dag check log without debug

* add unit test

* fix: add _no_pk_hash not null

* fix: TAP-4676 fix npe when ldap password is null

* add unit test for logging aspect task

* feat: preview performance and rpc count interface

* fix change master table schema on new partition table

* UPDATE RELEASE

* fix(iengine): Fix share cdc performance issue

(cherry picked from commit 6f28d549aaf72eaab57903a07968875d586390ca)

* feat: TAP-5046 migrate task should clean batch offset when remove current sync table and enter cdc stage

* feat: TAP-5046 resolve code smell

* feat: TAP-5046 resolve code smell add unit test

* fix(iengine): TAP-5241 The log mining task encountered a NullPointerException

Closes TAP-5241

* fix(iengine): TAP-5241 The log mining task encountered a NullPointerException

Closes TAP-5241

* fix: TAP-4676 support ad login by username

* TAP-5061:fix cloud Permission RoleMapping Large flow

* feat(iengine):TAP-5094 update error code

* fix(iengine):update unit case

* fix: TAP-5206 Multiple retries of shared mining task resulted in oom

* fix: TAP-5206 resolve sonar issue

* update query log api

* fix: TAP-5206 fix unit test failure

* support include log tag and exclude log tag

* add dynamic description parameters

* update unit case

* fix(iengine):update unit case

* fix(iengine):update error code

* fix: TAP-5206 Multiple retries of shared mining task resulted in oom

* fix(iengine):TAP-5228 inspect support boolean compare with not boolean value

* fix(iengine):add unit case

* fix(iengine):update unit case

* fix(iengine): change to boolean return value

* fix: TAP-5005 Revise the description of Maputls in the JS API documentation

* fix(tm):add some log

* fix not update milesone retry status when cdc finish

* fix(iengine): Fix polling cdc bug

exception: / by zero

* fix(tm):add some log

* fix(tm):add update log

* fix:js not found import class develop

* fix(tm):add log for tm

* TAP-5265:fix js not found import class develop

* TAP-5257:fix(tm): transformer will cover old task setting

* fix(tm):change SYNC_TYPE with constant

* fix(tm):convert string to constant

* fix(tm): exclusionQueryField type

* fix(tm):exclusion type

---------

Co-authored-by: Leon <lirufei0808@gmail.com>
Co-authored-by: harsen <harsen@tapdata.io>
Co-authored-by: mnianqi <mnq0626@163.com>
Co-authored-by: hardy <2545433047@qq.com>
Co-authored-by: ljvv7 <fes504200361@qq.com>
Co-authored-by: jarad0628 <coolgj@163.com>
Co-authored-by: jackin-code <452725950@qq.com>