fix(TAP-12550): Some node configurations were not loaded properly when the engine started, causing occasional issues
1. When scanning for registered node types in DAG static code blocks, the forEach catch range is too narrow (unable to catch Error subclasses such as NoClassDefFoundError), and it will silently interrupt traversal when encountering any dependent node classes that are not ready, resulting in TableNodes that are ranked after not having a chance to be registered in nodeMapping. The iteration order of Set<BeanDiagnosis>is not fixed with startup, so it appears as "sometimes normal and sometimes abnormal when restarting".
2. Swallowing exception logs without printing are all reasons for the exception
3. Lack of a fallback mechanism, failure becomes an irreversible outcome