Release v3.19.0 develop merge into main (#2416)
* TAP-5061:fix cloud Permission RoleMapping Large flow

* TAP-5061:fix cloud Permission RoleMapping Large flow

* feat: add dynamicDescriptionParameters for connection test

* feat: TAP-5152 Supported mongodb lower to mongodb IUD and Replace operations

* upgrade tapdata-pdk-api version to 1.4.1

* fix(task preview): unit tests

* fix(task preview): fix sonar bugs

* fix(task preview): unit tests

* TAP-4533:fix

* TAP-4533:fix

* fix(task preview): unit tests

* TAP-4533:fix

* fix(task preview): unit tests

* fix(task preview): unit tests

* fix(task preview): fix sonar bugs

* feat(iengine):update error code

* fix(iengine):update error code

* fix(iengine):update error code

* fix(iengine):fix unit case

* fix(iengine):fix unit case failed

* fix(iengine):update unit case

* fix(iengine):update unit case

* Fix merge issue and failed unit tests

* fix(iengine):update unit case

* fix(iengine):update unit case

* fix(iengine):add unit case

* fix(iengine):add unit case

* fix(iengine):add unit case

* fix: dynamic add table and ddl

* fix(iengine): Fix performance issue

The statistics module temporarily switches back to the old version logic to avoid affecting performance and awaits subsequent adjustments.

* fix(iengine): Change duplicate info logs to debug

* fix: TAP-5183 The task progress keeps showing 50%

* perf(iengine): TAP-5154 Master-slave merge improves logs to facilitate finding cache table names

Closes TAP-5154

* fix: TAP-5180 prompt no permission when delete tags by other user

* TAP-5061:fix cloud Permission RoleMapping Large flow

* Fix failed unit test

* fix: upgrade plugin pom

* TAP-5061:fix cloud Permission RoleMapping Large flow

* fix change table monitor associateId bug

* Fix can not create sub partition bug

* add unit test for restartPdkConnector

* add unit test for table monitor start method

* fix reliability rating on new code

* update unit test for table monitor start method

* fix: TAP-5190 Resolve the unauthorized access vulnerability of Spring Boot Actuator

* fix: TAP-5181 source node reload schema prompt System error: null

* refactor log storage

* TAP-5211:fix(TM):fix loading schema slow

* fix(tm):TAP-5211 loading schema slow

* fix(TM):TAP-5223 console dag check log without debug

* add unit test

* fix: add _no_pk_hash not null

* fix: TAP-4676 fix npe when ldap password is null

* add unit test for logging aspect task

* feat: preview performance and rpc count interface

* fix change master table schema on new partition table

* UPDATE RELEASE

* fix(iengine): Fix share cdc performance issue

(cherry picked from commit 6f28d549aaf72eaab57903a07968875d586390ca)

* feat: TAP-5046 migrate task should clean batch offset when remove current sync table and enter cdc stage

* feat: TAP-5046 resolve code smell

* feat: TAP-5046 resolve code smell add unit test

* fix(iengine): TAP-5241 The log mining task encountered a NullPointerException

Closes TAP-5241

* fix(iengine): TAP-5241 The log mining task encountered a NullPointerException

Closes TAP-5241

* fix: TAP-4676 support ad login by username

* TAP-5061:fix cloud Permission RoleMapping Large flow

* feat(iengine):TAP-5094 update error code

* fix(iengine):update unit case

* fix: TAP-5206 Multiple retries of shared mining task resulted in oom

* fix: TAP-5206 resolve sonar issue

* update query log api

* fix: TAP-5206 fix unit test failure

* support include log tag and exclude log tag

* add dynamic description parameters

* update unit case

* fix(iengine):update unit case

* fix(iengine):update error code

* fix: TAP-5206 Multiple retries of shared mining task resulted in oom

* fix(iengine):TAP-5228 inspect support boolean compare with not boolean value

* fix(iengine):add unit case

* fix(iengine):update unit case

* fix(iengine): change to boolean return value

* fix: TAP-5005 Revise the description of Maputls in the JS API documentation

* fix(tm):add some log

* fix not update milesone retry status when cdc finish

* fix(iengine): Fix polling cdc bug

exception: / by zero

* fix(tm):add some log

* add catch data feature

* fix(tm):add update log

* fix:js not found import class develop

* fix(tm):add log for tm

* TAP-5265:fix js not found import class develop

* update unit test case

* TAP-5257:fix(tm): transformer will cover old task setting

* add unit test case

* update unit test case

* optimization milestone describe error code

* fix(tm):change SYNC_TYPE with constant

* fix(tm):convert string to constant

* fix(tm): exclusionQueryField type

* fix(tm):exclusion type

* fix: fix for cloud version fully hosted public engine CPU usage rate of 100%

* fix: fix for cloud version fully hosted public engine CPU usage rate of 100%

* fix: fix for cloud version fully hosted public engine CPU usage rate of 100%

* feat(iengine): TAP-5906 update error code

* fix(iengine): Fix task preview npe bug

* fix(iengine):update error code

* feat(iengine): TAP-5906 update error code

* update data catch feature

* update query cache data by user input string

* feat(iengine): TAP-5906 update error code

* update unit test case

* update unit test case

* feat(iengine): TAP-5906 code review

* add table name into catch data

* feat(iengine): TAP-5906 fix unit test

* optimization catch data code

* optimization catch data code

* tapce workflow test

* tapce workflow test

* feat(TM):TAP-5253 add custom collate

* feat(iengine): TAP-5906 add unit test

* feat(iengine): TAP-5906 add unit test

* feat(iengine): TAP-3360 engine can start without mongodb config

* update catch data

* feat(iengine): TAP-3360 add unit test

* update data serialize config for ObjectId

* Update ConnectorManager.java

* feat(iengine):TAP-5253 support custom collate

* optimization json serialize for catch data

* feat(iengine): TAP-3360 add unit test

* fix(iengine):update unit case

* fix(iengine):remove unit case

* update unit test case

* fix(manager):add sonar config

* update processCompleted

* feat: TAP-5193 MongoDB supports SSL configuration connection

* feat(iengine): TAP-5193 MongoDB supports SSL configuration connection

* feat(iengine): TAP-5193 MongoDB supports SSL configuration connection

* optimization code for process tap event

* feat(iengine): TAP-3360 engine can start without mongodb config

* fix: add scan-tapdata into mr-ci.yaml

* add unit test case

* fix: TAP-5304 admin user allows to operate all tags

* feat(iengine): TAP-3360 resolve sonar issue

* feat: TAP-5193 resolve sonar issue

* update unit test

* fix: TAP-5304 add unit test

* Fix merge issue

* Fix merge issue

* fix:TAP-5331_task_index_error

* Fix batch offset status issue

* fix: TAP-5193 update ssl environment variables name

* fix:TAP-5331_task_index_error

* fix:TAP-5331_task_index_error

* fix:TAP-5331_task_index_error

* feat: TAP-5286 optimize ad login exception

* fix: TAP-5193 fix log mongo config

* Fix batch offset status issue

* Fix target throw error issue

* fix: TAP-4874 Fixed a situation where disabling a source node in the merge scenario could not be completed.

* fix: TAP-5250 After the indicator is cleared by ttl, the dynamically added table of the copy task does not work

* fix: TAP-5250 After the indicator is cleared by ttl, the dynamically added table of the copy task does not work

* feat: TAP-5286 optimize ad login exception

* Fix rename fields bug

* TAP-5350 fix(tm): Migrating tasks The migration task time injection is empty

* fix:js model deduction failed

* fix:js model deduction failed

---------

Co-authored-by: hardy <2545433047@qq.com>
Co-authored-by: jarad0628 <coolgj@163.com>
Co-authored-by: harsen <harsen@tapdata.io>
Co-authored-by: Leon <lirufei0808@gmail.com>
Co-authored-by: jackin-code <452725950@qq.com>
Co-authored-by: ljvv7 <fes504200361@qq.com>
Co-authored-by: mnianqi <mnq0626@163.com>
Co-authored-by: zhoupeng <peng@tapdata.io>
Co-authored-by: mnianqi <139107099+mnianqi@users.noreply.github.com>
Co-authored-by: dreamcoin1998 <gaojunbin98@gmail.com>